### ISSUE TITLE
octopi-helper[aborted]: Suspicious execution method

### ISSUE THREAD

**Issue by bcoolumbo1** [aarnt/octopi#400] opened 2019-11-15 13:28 UTC
octopi-helper[aborted]: Suspicious execution method

Error message on arch linux.
I downloaded octopi from git (because the repo version does not work too)

**Comment by aarnt** [comment] 2019-11-15 14:53
@bcoolumbo1 
Upstream code is under a lot of changes.
Be very careful at using the dev code in these days.
For instance, you no longer will be able to exec octopi under any different path than "/usr/bin".

**Comment by rtizzy** [comment] 2020-01-15 14:29
@aarnt 

Is there anyway this issue can be reopened? It's a few months later and I'm still experiencing this issue myself. 

Currently managing things at the CLI until it's fixed. 

I am experiencing this issue on the Stable version of Manjaro KDE edition.

**Comment by aarnt** [comment] 2020-01-15 14:46
@rtizzy 
If you mean when you run octopi thru terminal it works but when you open using plasma menu or shortcuts it doesn't... that's because ".desktop" files need to be updated to reflect Octopi tool full path ("/usr/bin/[octopi | octopi-notifier | octopi-cachecleaner]").
You can find those ".desktop" files and change yourself to test.
Then if it woks, you can open a Manjaro issue.

**Comment by rtizzy** [comment] 2020-01-21 16:00
Howdy @aarnt 

Took a look and that seems to be set correctly. 

![image](https://user-images.githubusercontent.com/523926/72820519-61ea4180-3c6f-11ea-8705-bbb8bfcf20f6.png)

On the other hand, when running from Terminal, I now get a segmentation fault when attempting to install updates

1. Refresh to find packages need updates. 
2. Click and select install in the bottom right corner. 
3. Click run in terminal.
4. Below error output. 

```
~ ❯❯❯ octopi
Trying to load translation file from dir "/home/rtisdale/.local/share/flatpak/exports/share"
Trying to load translation file from dir "/var/lib/flatpak/exports/share"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
[1]    3518 segmentation fault (core dumped)  octopi
```

**Comment by aarnt** [comment] 2020-01-21 17:15
Are you using latest code compiled by tou or someone else pkg?

**Comment by rtizzy** [comment] 2020-01-21 17:19
Howdy @aarnt 

This is version 0.9.0-21 packaged by the Manjaro maintainer (philm@manjaro.org in this cas)

**Comment by aarnt** [comment] 2020-01-21 17:25
Hum, I do not know which version he used. Can you get Pkgbuild and octopi.install from here and build yourself?

**Comment by aarnt** [comment] 2020-01-21 17:36
Also try to remove any /tmp/"arnt* file you may have before running octopi.

**Comment by evertonstz** [comment] 2020-02-11 13:26
I have the same problem on manjaro.

**Comment by muhammetsait** [comment] 2020-02-26 05:54
Hey everyone,

I had this issue on Manjaro (KDE Plasma) after a recent update. Solved by completely removing octopi and notifier then reinstalling & reboot:

```bash
sudo pacman -Rnsc octopi
sudo pacman -S octopi octopi-notifier-frameworks
reboot
```

**Comment by gwarser** [comment] 2020-02-29 00:59
Thanks @muhammetsait, your solution seems to work.

**Comment by gwarser** [comment] 2020-03-01 23:16
Aaaaand stopped working :(

**Comment by rtizzy** [comment] 2020-03-02 06:53
@gwarser 
@muhammetsait
@evertonstz 
@aarnt 

Hey folks. 

I did a bit more poking around and I'm relatively certain this will be a distribution specific issue. 

**Is anyone who IS NOT using Arch (or a derivative such as Manjaro) experiencing this issue?**

Here is what I found:

1. My desktop files are pointing at the right directories as seen in screenshots [here](https://github.com/aarnt/octopi/issues/400#issuecomment-576750269).
2. If I run Octopi directly in the terminal via the following (Correct) path, the program works as expected and will allow me to upgrade
```
/usr/bin/octopi
```
3. With that said, a `which octopi` shows the following. 
```
~ ❯❯❯ which octopi                                                                                                                                                   ✘ 130 
/bin/octopi
```

I believe this has something to do with how the $PATH is being resolved and in particular, is something wrong with how things are packaged on Manjaro. 

My bet is the other systems experiencing this issue will also have `octopi`s path resolve to `/bin/octopi`

**A temporary fix:**

Run octopi via the CLI via the correct path and things will work as expected.

**Comment by rtizzy** [comment] 2020-03-02 07:15
Something that may be related to this: 

/bin is first in my path. Arch Linux has a weird thing where bin is symlinked to /usr/bin.

**Comment by aarnt** [comment] 2020-03-02 20:15
@rtizzy 
@gwarser 
@muhammetsait 

I downloaded Manjaro 19 plasma ed and installed it in a VM.
Got qtermwidget and alpm-octopi-utils from Manjaro's repo and cloned Octopi github repo.

First built and installed sudo and helper then built and installed Octopi.
All working fine here. No issues at all.

**Comment by gwarser** [comment] 2020-03-02 23:24
To be clear, I see this only when executed from tray, when update is available:
	
	[rdk@on ~]$ sudo /usr/lib/octopi/octphelper -ts                                                                                     
	[sudo] password for rdk: 
	
	octopi-helper[aborted]: Suspicious execution method

Maybe it's about this `octphelper` and not directly `octopi`?

I think this started happening to me with this new custom terminal window with this confusing always-on search bar.

**Comment by aarnt** [comment] 2020-03-03 00:24
@gwarser 

Hmm,
Then close this notifier and open another from a terminal: 

`/usr/bin/octopi-notifier`

Try to execute the update then.

**Comment by gwarser** [comment] 2020-03-03 11:03
So it seems it's caused by desktop session restore feature. There is long alphanumeric `-session` parameter added to `octopi-notifier` when started with system. Adding `octopi-notifier` to list of applications to be excluded from sessions seems to fix this for me.

**Comment by pho7on** [comment] 2020-03-14 12:42
> So it seems it's caused by desktop session restore feature. There is a long alphanumeric `-session` parameter added to `octopi-notifier` when started with system. Adding `octopi-notifier` to list of applications to be excluded from sessions seems to fix this for me.

Could you please elaborate a little bit more?

**Comment by gwarser** [comment] 2020-03-14 14:23
If you open System Monitor and filter for "octopi-notifier" you will see something like this:

![image](https://user-images.githubusercontent.com/886325/76683787-0a30dc80-6607-11ea-8122-706f30cc71d8.png)

but with `-session 1234589abcdef12345678909abcdef` appended to the `/us/bin/octopi-notifier` command.

You can go to the System Settings -> Startup and Shutdown -> Desktop Session, and turn session restore feature "off" or just ad "octopi-notifier" to the list of "Applications to be excluded from session":

![image](https://user-images.githubusercontent.com/886325/76683859-80354380-6607-11ea-9cba-f552fd560056.png)

**Comment by pho7on** [comment] 2020-03-14 15:44
@gwarser thanks a lot!

**Comment by jowilhnson** [comment] 2020-03-20 17:19
None of these worked for me, aside from running from cli. 
Neither remove / reinstall, nor excluding from desktop session restore seem to be working at this point.

**Comment by aarnt** [comment] 2020-03-20 20:07
@jowilhnson 
So we have no choice other than reopening...

**Comment by pavanmehta91** [comment] 2020-03-25 18:37
@gwarser Startup trick did work. Thanks :)

**Comment by mputterf** [comment] 2020-03-30 05:39
This same error happens when you install a package from the AUR and then immediately try to remove it without closing and reopening octopi first.

**Comment by aarnt** [comment] 2020-03-30 22:23
Thanks @mputterf !
Fixed on upstream:
https://github.com/aarnt/octopi/commit/1eff031e23b77135a5db87e8cd5dff9cdf64255f

**Comment by aarnt** [comment] 2020-05-26 20:10
@bcoolumbo1 
Everything fine now?

**Comment by aarnt** [comment] 2020-10-11 10:56
Closing due to lack of feedback.

**Closed by aarnt** 2020-10-11 10:56 UTC

**Comment by LinuxCuba** [comment] 2020-10-15 13:26
thanks you.
Best regards

**Comment by aarnt** [comment] 2020-10-15 13:38
> thanks you.
> Best regards

@LinuxCuba 
You are having this error with Octopi 0.10?

**Comment by gwarser** [comment] 2020-10-21 22:05
Still an issue: 
![image](https://user-images.githubusercontent.com/886325/96792202-382a9a80-13fa-11eb-8d2e-f2d17714d8ef.png)

**Comment by aarnt** [comment] 2020-10-21 22:26
@gwarser 
Octopi helper is not meant to be executed manually. If you do so in a terminal, it'll always abort with that error msg.

This helper is called by octopi tools only.

**Comment by gwarser** [comment] 2020-10-21 22:52
Click icon in tray -> click "Run in terminal". I always run it like this, and it's fine as long there is no `-session` parameter added to `octopi-notifier`. I removed it from desktop restore exclusions last week for testing.

![image](https://user-images.githubusercontent.com/886325/96798133-82af1580-1400-11eb-9abc-e96552cd2c98.png)

**Comment by aarnt** [comment] 2020-10-22 12:54
@gwarser 
Thanks for the clarification.
So the command that runs in the system is "/usr/bin/octopi-notifier -session" (ps -aux output)?

**Comment by gwarser** [comment] 2020-10-22 15:54
![image](https://user-images.githubusercontent.com/886325/96898115-a4a3a900-148f-11eb-900e-fd3908690c32.png)

**Comment by aarnt** [comment] 2020-10-22 18:29
@gwarser 
Could you test latest commit https://github.com/aarnt/octopi/commit/af881e7912f4a29d0d230efb90ef9826127defd2 ?

**Comment by gwarser** [comment] 2020-10-22 21:00
Is it enough to compile and install only the helper?

By distraction I compiled and installed notifier first, but it did not work. Then I noticed that it was helper that was changed and after compiling and installing it seems to work - just tested on Firefox update.

**Comment by aarnt** [comment] 2020-10-22 21:03
@gwarser 
Yes, for this commit only helper is needed.
Thank you!
