### ISSUE TITLE
[Bug/Suggestion - UX] Octopi always start in background

### ISSUE THREAD

**Issue by piotrekkr** [aarnt/octopi#399] opened 2019-11-12 17:03 UTC
After right clicking on octopi icon and selecting update, Octopi update window starts in background. If I have firefox opened and then select update in Octopi icon menu it starts under Firefox window in KDE plasma. I have to double click it on task bar, first click minimize octopi window, second click to restore in foreground. It should always start in foreground and with focus on window as every other app in kde :)

Manjaro + KDE Plasma

**Comment by MatMoul** [comment] 2019-11-20 21:43
@piotrekkr Is this always the case?
I've encountered the same issue but after updating .desktop files it seem this is resolved.
Can you confirm?

**Comment by piotrekkr** [comment] 2019-11-20 21:53
@MatMoul What do you mean by "after updating .desktop files"? I'll see if this behaviour still remains when octopi tray icon will appear again. I'll let you know. Or is there a way to force Octopi icon to show up?

**Comment by MatMoul** [comment] 2019-11-20 21:56
@piotrekkr This recent commit : 7b3ccfb67dd188d950098d5f18eb8243079a91ff
After this closed issue #402

**Comment by piotrekkr** [comment] 2019-11-20 22:05
@MatMoul ok I'm not really sure if it is related but I've changed paths in those desktop files and I'll let you know if it works (when some updates will show up).

**Comment by MatMoul** [comment] 2019-11-20 22:07
@piotrekkr I test it with the downgrade package...
You can wait but don't miss to give you feedback

**Comment by piotrekkr** [comment] 2019-11-20 22:21
Sadly this is not working (see screen). I've right clicked octopi icon and then system upgrade. 
![Screenshot_20191120_231309](https://user-images.githubusercontent.com/503782/69283075-01497480-0bec-11ea-8d79-0fcf5cf66569.png)

**Comment by MatMoul** [comment] 2019-11-20 22:29
@piotrekkr I see it...
Very strange, i've made many tests with one FF open and more than one FF open without problem...
Waht your OS and do you use the AUR version?

**Comment by piotrekkr** [comment] 2019-11-20 22:35
My specs:
```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.3
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.2
Kernel Version: 5.3.11-1-MANJARO
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 1700X Eight-Core Processor
Memory: 15,7 GiB of RAM
```
Firefox:
![image](https://user-images.githubusercontent.com/503782/69284153-35259980-0bee-11ea-9540-be7cb013065f.png)
It is not related to firefox. Same thing happens with thunderbird, gimp, krusader and more apps.

**Comment by MatMoul** [comment] 2019-11-20 22:46
Ok if you're on manjaro, you need to wait an update of octopi...
If you want to have the dev release, you need to install octopi-dev and octopi-notifier-.. in AUR

**Comment by MatMoul** [comment] 2019-11-23 02:16
Unfortunately the issue is still there (octopi-notifier-framwork)...

Click in menu that work (octopi)
Click in menu that doesn't work (all other)

Reproduce :
Start an app click to focus it then right click to octopi-notifier and click about or option or update, the window start in background

**Comment by piotrekkr** [comment] 2019-11-23 07:43
@MatMoul Just installed new version of octopi and octopi framework:
```
$ pacman -Qe | grep octopi
octopi 0.9.0-20
octopi-notifier-frameworks 0.9.0-20
```
and about octopi
```
Octopi Notifier
Version: 0.9.0-20 (git-529a86) - Qt 5.13.2
URL: http://octopiproject.wordpress.com
Licenses: GPL v2
© Alexandre Albuquerque Arnt

Pacman
Version: 5.2.1
URL: https://www.archlinux.org/pacman
© 2006-2019 Pacman Development Team
© 2002-2006 Judd Vinet
```

Issue still remains...

**Comment by MatMoul** [comment] 2019-11-24 03:05
After some investiagation, I found this :
If octopi-notifier is started with /etc/xdg/autostart/octopi-notifier.desktop, I have the issue.
If I close octopi-notifier and restart it with the kde menu, focus is working each time.

I don't know how this can be solved in the code, maybe a raise() on the mainwindow before runoctopi() and aboutOctopiNotifier()

**Comment by MatMoul** [comment] 2019-11-25 23:13
After some research, I found the case...
It's due to the Focus Stealing Prevention in KWin...
By default the setting is set to low and this require an update of _NET_WM_USER_TIME (https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html) before show a window...
Setting this setting to none solve the issue or adding a custom window rules solve it too...
I don't know how is possible to update _NET_WM_USER_TIME in the code

**Comment by aarnt** [comment] 2020-01-02 18:13
@piotrekkr and @MatMoul 

Could you test latest code from https://github.com/aarnt/octopi/commit/b8bf9495d05509e91de963a2ec4173100c0e84e6 ?

**Comment by piotrekkr** [comment] 2020-01-02 20:29
@aarnt I would like to do this but I'm not familiar with compiling and installing Octopi on Arch/Manjaro. Is there any readme about how to do this?

**Comment by aarnt** [comment] 2020-01-02 22:00
Just download https://github.com/aarnt/octopi/blob/master/PKGBUILD and https://github.com/aarnt/octopi/blob/master/octopi.install and issue a "makepkg -f" on the directory they are located.

That command will produce a package called octopi that you just need to "pacman -U" it.

**Comment by MatMoul** [comment] 2020-01-03 05:01
@aarnt I've just build a new release of octopi-dev and tested it...
Now the update window always open on top but stay always on top even when you select an another window before update.
It's still a better solution...

**Comment by aarnt** [comment] 2020-01-03 09:52
@MatMoul 
Yes, this is by design so the modal Window never gets forgotten.

**Comment by aarnt** [comment] 2020-01-03 23:05
@demmm found that bug report: https://bugs.kde.org/show_bug.cgi?id=414022
So with the information we collect here and the implemented "stay on top" workaround I'll close this one.

**Closed by aarnt** 2020-01-03 23:05 UTC
