### ISSUE TITLE
IgnorePkg ignored

### ISSUE THREAD

**Issue by slaecker** [aarnt/octopi#57] opened 2014-12-07 11:32 UTC
I have the following entry in /etc/pacman.cfg:
> IgnorePkg = freerdp

But Octopi 0.5.0 on ArchLinux with KDE 4 keeps showing 1 update after completely updating the system

> $ pacman -Syu
> Nothing to do

After Octopi database synchronization Octopi-Notifier still shows 1 update, launching Octopi shows the freerdp update.

> 
freerdp 1.1.0_beta+2013071101-1 1.2.0_beta1+android9-1

**Comment by Kirek** [comment] 2015-03-03 14:53
I think this is solved I cannot reproduce with latest Octopi version in Manjaro. IgnoreGroup its not used though. I will open a new issue.

**Comment by Gyges88** [comment] 2015-03-16 17:47
Hi there!
IgnorePkg is still ignored in the latest version (0.6.0-2) using Manjaro LXQT.
As you can see from the image attached the two packages manually added to IgnorePkg are still adding to the number of updates shown by Octopi.
Cheers

Gyges
![octopi](https://cloud.githubusercontent.com/assets/4368901/6672435/cfede020-cc0c-11e4-9c50-3085103ad4ba.png)

**Comment by aarnt** [comment] 2015-03-16 21:29
hi Gyges,
Please, post the result of this command:
"yaourt -Qua | grep aur/"

**Comment by Gyges88** [comment] 2015-03-18 10:46
Sure:
[Gyges@desktop ~]$ yaourt -Qua | grep aur/
aur/bin32-lightscribe 1.18.27.10-2

Cheers

**Comment by Gyges88** [comment] 2015-03-20 17:46
Oh foolish me! I grabbed the wrong device (desktop instead of laptop).
The right output is:
[gyges@s3nlap ~]$ yaourt -Qua | grep aur/
aur/lxmenu-data-git 0.0.0.1-1
aur/spotify 0.9.11.27-3
So these are the two entries I've added manually (freetype2 and fontconfig are default entries).
Guess that's makes much more sense, doesn't it?
Sorry for the confusion!

**Comment by aarnt** [comment] 2015-03-20 17:50
Ok, can you test if GitHub version fix your issues?

**Comment by Gyges88** [comment] 2015-03-20 18:29
Sure. Will test tomorrow.
Cheers

**Comment by Gyges88** [comment] 2015-03-21 20:14
Well,
the good news is it works like a charm now, as you can see from the images below.
Bad news is that I'm a little confused. Because even before I've upgraded from Octopi-0.6.0-2 to 0.6.0-6 (based on Octopi git 73b684d231722181cbc2f8507fb5cd74f3695a78) today, the issue that is being discussed here was automagically gone.
However, version 0.6.0-2 is from 3/1 as my logs show:
[2015-03-01 18:54] [ALPM] upgraded octopi (0.6.0-0 -> 0.6.0-2)
So perhaps this was a Manjaro issue after all?
Anyway, it seems IgnorePkg is no longer ignored (as of octopi-0.6.0-6 at least) !
Good job, everybody!

![octopi-0 6 0-2-noupdates](https://cloud.githubusercontent.com/assets/4368901/6766648/c343c280-d00e-11e4-94df-19ad71230e43.png)

![octopi-0 6 0-2-updates](https://cloud.githubusercontent.com/assets/4368901/6766651/ccde6f70-d00e-11e4-8fcd-a956b931e832.png)

**Comment by ZeroBit** [comment] 2015-03-22 10:39
I use archlinux and have the same problem: Octopi doesn't ignore packages in IgnorePkg in /etc/pacman.conf
$ pacman -Qs octopi
local/octopi 0.6.0-1
    a powerful Pacman frontend using Qt libs
local/octopi-cachecleaner 0.6.0-1
    Cachecleaner for Octopi
local/octopi-notifier 0.6.0-1
    Notifier for Octopi
local/octopi-repoeditor 0.6.0-1
    Pacman repo editor for Octopi

With octopi-git version the situation is the same. 
![octopi](https://cloud.githubusercontent.com/assets/6258813/6768993/82e60a18-d090-11e4-93b7-0d6c3ec63875.png)

**Comment by aarnt** [comment] 2015-03-22 13:48
Hi ZeroBit, could you try the latest git version? I've made a change.

**Comment by ZeroBit** [comment] 2015-03-22 14:01
Now it works fine! Thank you for fixing.
![octopi2](https://cloud.githubusercontent.com/assets/6258813/6769611/9c2d6414-d0ac-11e4-98dd-82e3e4f558c5.png)

**Comment by aarnt** [comment] 2015-03-22 14:19
Nice.
I'll close this issue for now.

**Closed by aarnt** 2015-03-22 14:19 UTC

**Comment by Gyges88** [comment] 2015-03-22 14:28
Just for the record: the latest git version (0.7.0) works for me, too.
Thank you!

**Comment by Termuellinator** [comment] 2020-12-30 11:25
I'm encountering this issue now for the first time - i downgraded before and it never happend, but now i downgraded systemd-swap and added it to ignorepkg, but still octopi and octopi-notifier state it as a pending update.
Current Manjaro-Testing, Octopi Version: 0.10.0 - Qt 5.15.1, Pacman Version: 5.2.2
